# Copyright 2020-2024 The MathWorks, Inc.

name: Run MATLAB Tests
description: >-
  Run MATLAB and Simulink tests and generate artifacts
inputs:
  source-folder:
    description: >-
      Location of the folder containing source code
    required: false
    default: ""
  strict:
    description: >
      Whether to apply strict checks when running the tests.
    required: false
    default: false
  use-parallel:
    description: >-
      Whether to run tests in parallel
    required: false
    default: false
  output-detail:
    description: >
      Display level for event details produced by the test run
    required: false
    default: ""
  logging-level:
    description: >
      Maximum verbosity level for logged diagnostics included for the test run
    required: false
    default: ""
  select-by-folder:
    description: >-
      Location of the folder containing test files
    required: false
    default: ""
  select-by-tag:
    description: >-
      Test tag used to select test suite elements
    required: false
    default: ""
  test-results-pdf:
    description: >-
      File path to write test results in PDF format
    required: false
    default: ""
  test-results-html:
    description: >-
      Folder path to write test results in HTML format
    required: false
    default: ""
  test-results-junit:
    description: >-
      File path to write test results in JUnit-style XML format
    required: false
    default: ""
  test-results-simulink-test:
    description: >-
      File path to export Simulink Test Manager results in MLDATX format
    required: false
    default: ""
  code-coverage-cobertura:
    description: >-
      File path to write code coverage results in Cobertura XML format
    required: false
    default: ""
  code-coverage-html:
    description: >-
      Folder path to write code coverage results in HTML format
    required: false
    default: ""
  model-coverage-cobertura:
    description: >-
      File path to write model coverage results in Cobertura XML format
    required: false
    default: ""
  model-coverage-html:
    description: >-
      Folder path to write model coverage results in HTML format
    required: false
    default: ""
  startup-options:
    description: >-
      Startup options for MATLAB
    required: false
    default: ""
runs:
  using: node20
  main: dist/index.js
