# Copyright 2020 The MathWorks, Inc.

name: Run MATLAB Tests
description: >-
  Run MATLAB and Simulink tests and generate artifacts
inputs:
  source-folder:
    description: >-
      Location of the folder containing source code
    required: false
    default: ""
  select-by-folder:
    description: >-
      Location of the folder containing test files
    required: false
    default: ""
  select-by-tag:
    description: >-
      Test tag used to select test suite elements
    required: false
    default: ""
  test-results-pdf:
    description: >-
      Path to write test results report in PDF format (not supported on macOS)
    required: false
    default: ""
  test-results-junit:
    description: >-
      Path to write test results report in JUnit XML format
    required: false
    default: ""
  test-results-simulink-test:
    description: >-
      Path to export Simulink Test Manager results in MLDATX format
    required: false
    default: ""
  code-coverage-cobertura:
    description: >-
      Path to write code coverage report in Cobertura XML format
    required: false
    default: ""
  model-coverage-cobertura:
    description: >-
      Path to write model coverage report in Cobertura XML format (requires
      MATLAB R2018b or later)
    required: false
    default: ""
runs:
  using: node12
  main: dist/index.js
