# Copyright 2020-2022 The MathWorks, Inc.

name: Run MATLAB Tests
description: >-
  Run MATLAB and Simulink tests and generate artifacts
inputs:
  source-folder:
    description: >-
      Location of the folder containing source code
    required: false
    default: ""
  strict:
    description: >
      Whether to apply strict checks when running the tests.
    required: false
    default: false
  use-parallel:
    description: >-
      Whether to run tests in parallel
    required: false
    default: false
  output-detail:
    description: >
      Display level for event details produced by the test run
    required: false
    default: ""
  logging-level:
    description: >
      Maximum verbosity level for logged diagnostics included for the test run
    required: false
    default: ""
  select-by-folder:
    description: >-
      Location of the folder containing test files
    required: false
    default: ""
  select-by-tag:
    description: >-
      Test tag used to select test suite elements
    required: false
    default: ""
  test-results-pdf:
    description: >-
      Path to write test results report in PDF format
    required: false
    default: ""
  test-results-junit:
    description: >-
      Path to write test results report in JUnit XML format
    required: false
    default: ""
  test-results-simulink-test:
    description: >-
      Path to export Simulink Test Manager results in MLDATX format
    required: false
    default: ""
  code-coverage-cobertura:
    description: >-
      Path to write code coverage report in Cobertura XML format
    required: false
    default: ""
  model-coverage-cobertura:
    description: >-
      Path to write model coverage report in Cobertura XML format
    required: false
    default: ""
runs:
  using: node16
  main: dist/index.js
